### ISSUE TITLE
Invalid glob argument

### ISSUE THREAD

**Issue by brycepj** [ck86/main-bower-files#1]
When I add main-bower-files to my gulpfile, using your example: 

```

gulp.task('bower', function() {
    return gulp.src(mainBowerFiles())
        .pipe(gulp.dest('lib'));
});

```

I am getting an "invalid glob argument". 

Here's what it looks like. 

```
Error: Invalid glob argument
    at Gulp.src (/Users/bryce/repo/jf/client/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:17:11)
    at Gulp.<anonymous> (/Users/bryce/repo/jf/client/gulpfile.js:31:17)
    at module.exports (/Users/bryce/repo/jf/client/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:33:7)
    at Gulp.Orchestrator._runTask (/Users/bryce/repo/jf/client/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/bryce/repo/jf/client/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/bryce/repo/jf/client/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:121:20
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

Any idea what's going on?

**Comment by jonathanpmartins** [comment]
Thanks for the TIP!! Help me out here!!!!!!!!!!!!!! :dancer:

**Comment by sialaweb** [comment]
thanks ck86

**Comment by blade254353074** [comment]
Thanks @ck86

**Comment by raviji** [comment]
thanks a lot its working, you saved my day

**Comment by lakshmankotipalli** [comment]
Thanks @ck86  It is the reason :+1:

**Comment by smit1529** [comment]
### **Make sure your local version of gulp is not 4.0.0**

If the local version of gulp is 4.0.0 then change into the package.json and make the configuration to 3.9.1 and try **npm install --save** and then try **gulp serve**

**This will do the trick.**

**Comment by manuman94** [comment]
Just like @smit1529 said! Thank you!

Is this a bug or is there another new way to specify files blob?

Greetings.

**Comment by gomarion** [comment]
> ### **Make sure your local version of gulp is not 4.0.0**
> If the local version of gulp is 4.0.0 then change into the package.json and make the configuration to 3.9.1 and try **npm install --save** and then try **gulp serve**
> 
> **This will do the trick.**

Yeah I was wondering about the same thing. Is this a bug in gulp 4.0.0? Because it now works when I rolled back to 3.9.1. And thank you, btw!! @smit1529
