### ISSUE TITLE
it should not error if no bower directory found

### ISSUE THREAD

**Issue by stevemao** [ck86/main-bower-files#103]
Because when there is no bower deps it will not create a bower_components folder
https://github.com/ck86/main-bower-files/blob/master/lib/index.js#L76

**Comment by TrySound** [comment]
@stevemao If you will pass function as last argument it will get an error object. And main-bower-files will return empty array.

**Comment by stevemao** [comment]
Sorry I'm using it with gulp, so i did `bower install` but nothing happens as there's no deps, and I do `gulp fonts` then errors are thrown.

```js
gulp.task('fonts', () => {
  return gulp.src(require('main-bower-files')({
    filter: '**/*.{eot,svg,ttf,woff,woff2}'
  }).concat('app/fonts/**/*'))
    .pipe(gulp.dest('.tmp/fonts'))
    .pipe(gulp.dest('dist/fonts'));
});
```

```
[16:26:07] 'fonts' errored after 81 ms
[16:26:07] Error: Bower components directory does not exist at /Users/stevemao/Documents/pub_games/dice/bower_components
    at Error (native)
    at module.exports (/Users/stevemao/Documents/pub_games/dice/node_modules/main-bower-files/lib/index.js:76:71)
    at Gulp.<anonymous> (/Users/stevemao/Documents/pub_games/dice/gulpfile.babel.js:74:46)
    at module.exports (/Users/stevemao/Documents/pub_games/dice/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/stevemao/Documents/pub_games/dice/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/stevemao/Documents/pub_games/dice/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/stevemao/Documents/pub_games/dice/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
```

**Comment by TrySound** [comment]
@stevemao I meant this
```
gulp.task('fonts', () => {
  return gulp.src(require('main-bower-files')('**/*.{eot,svg,ttf,woff,woff2}', function (err) {})
        .concat('app/fonts/**/*'))
    .pipe(gulp.dest('.tmp/fonts'))
    .pipe(gulp.dest('dist/fonts'));
});
```

**Comment by TrySound** [comment]
@stevemao And main-bower-files can't read deps from bower_components, it gets them from bower.json. So, you should to use `bower i pkg --save`.

**Comment by stevemao** [comment]
Thanks. There is nothing in the bower_components nor bower.json. Thanks for the correct suggestion of the gulpfile. Maybe this should go to README.md? feel free to close this :D

**Comment by ck86** [comment]
@stevemao Why should I use main-bower-files without bower dependencies? It makes no sense for me.
