### ISSUE TITLE
gulp.dest not a function

### ISSUE THREAD

**Issue by jamezilla0** [ck86/main-bower-files#131]
Hey there, I am really excited to use this module! As it will allow me to easily use browserify with bower-components, however I am now stuck. I get this error when ever I try to run a test task using the module. Here is my test task.

```javascript
var mainBowerFiles = require('main-bower-files');
var files = mainBowerFiles();

console.log(files)
gulp.task('bower-resolve', function(){
	return gulp.src(files, {base: 'public/bower_components'})
			   .pipe(function(files){
			   		console.log(files);
			   		return files;
			   })
			   .pipe(gulp.dest('tests/bower-resolve.js'));
})
```

Here is the output
```console
[ 'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular\\angular.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-socket-io\\socket.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-route\\angular-route.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\Chart.js\\Chart.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-chart.js\\dist\\angular-chart.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-chart.js\\dist\\angular-chart.css' ]
[05:49:43] 'bower-resolve' errored after 71 ms
[05:49:43] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (C:\nodeApps\sslho-node\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:516:8)
    at Gulp.<anonymous> (C:\nodeApps\sslho-node\gulpfile.js:27:8)
    at module.exports (C:\nodeApps\sslho-node\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\nodeApps\sslho-node\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\nodeApps\sslho-node\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\nodeApps\sslho-node\node_modules\orchestrator\index.js:134:8)
    at C:\Users\james\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
    at Function.Module.runMain (module.js:459:11)
```

P.S I still receive an error when I do exclude "pipe(gulp.dest(path))"

**Comment by jamezilla0** [comment]
I fixed the issue my self, I was not returning a proper gulp stream, so I used tap to help with that.

New code

```javascript
gulp.task('bower-resolve', function(){
	var files = mainBowerFiles();

	console.log(files);
	gulp.src(files)
			   .pipe(plumber())
			   .pipe(tap(function(files){
			   		console.log(files);
			   }))
			   .pipe(gulp.dest('tests/bower-resolve.js'));
});
```
Output

```console
PS C:\nodeApps\sslho-node> gulp bower-resolve
[06:01:45] Using gulpfile C:\nodeApps\sslho-node\gulpfile.js
[06:01:45] Starting 'bower-resolve'...
[ 'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular\\angular.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-socket-io\\socket.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-route\\angular-route.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\Chart.js\\Chart.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-chart.js\\dist\\angular-chart.js',
  'C:\\nodeApps\\sslho-node\\public\\bower_components\\angular-chart.js\\dist\\angular-chart.css' ]
[06:01:45] Finished 'bower-resolve' after 55 ms
<File "angular.js" <Buffer 2f 2a 2a 0d 0a 20 2a 20 40 6c 69 63 65 6e 73 65 20 41 6e 67 75 6c 61 72 4a 53 20 76 31 2e 32 2e 31 34 0d 0a 20 2a 20 28 63 29 20 32 30 31 30 2d 32 30 ..
. >>
<File "socket.js" <Buffer 2f 2a 0d 0a 20 2a 20 61 6e 67 75 6c 61 72 2d 73 6f 63 6b 65 74 2d 69 6f 20 76 30 2e 33 2e 30 0d 0a 20 2a 20 28 63 29 20 32 30 31 34 20 42 72 69 61 6e ...
 >>
<File "angular-route.js" <Buffer 2f 2a 2a 0d 0a 20 2a 20 40 6c 69 63 65 6e 73 65 20 41 6e 67 75 6c 61 72 4a 53 20 76 31 2e 32 2e 31 34 0d 0a 20 2a 20 28 63 29 20 32 30 31 30 2d 32
 30 ... >>
<File "Chart.js" <Buffer 2f 2a 21 0a 20 2a 20 43 68 61 72 74 2e 6a 73 0a 20 2a 20 68 74 74 70 3a 2f 2f 63 68 61 72 74 6a 73 2e 6f 72 67 2f 0a 20 2a 20 56 65 72 73 69 6f 6e 3a ...
>>
<File "angular-chart.js" <Buffer 28 66 75 6e 63 74 69 6f 6e 20 28 66 61 63 74 6f 72 79 29 20 7b 0a 20 20 27 75 73 65 20 73 74 72 69 63 74 27 3b 0a 20 20 69 66 20 28 74 79 70 65 6f
 66 ... >>
<File "angular-chart.css" <Buffer 2e 63 68 61 72 74 2d 6c 65 67 65 6e 64 2c 0a 2e 62 61 72 2d 6c 65 67 65 6e 64 2c 0a 2e 6c 69 6e 65 2d 6c 65 67 65 6e 64 2c 0a 2e 70 69 65 2d 6c 6
5 67 ... >>
PS C:\nodeApps\sslho-node>
```

**Comment by TrySound** [comment]
@jamezilla0 You should return stream to specify when the task will be end. `.pipe` always gets stream not function. And this is not bower issue.

**Comment by jrgleason** [comment]
I am having the same issue and I am confused by this answer is there an example?

**Comment by ck86** [comment]
Can you provide your gulp task?

**Comment by jrgleason** [comment]
```
var gulp = require('gulp'),
    flatten = require('gulp-flatten'),
    order = require("gulp-order"),
    concat = require("gulp-concat"),
    mainBowerFiles = require('main-bower-files');


gulp.task('build-dependencies', function() {
  console.log(mainBowerFiles("**/*.js"));
  return gulp.src('bower.json')
    .pipe(mainBowerFiles("**/*.js"))
    .pipe(flatten())
   .pipe(gulp.dest('public/javascripts'));
});

```

**Comment by jrgleason** [comment]
commenting out the mainBowerFiles makes it work

**Comment by ck86** [comment]
```js
var gulp = require('gulp'),
    flatten = require('gulp-flatten'),
    order = require("gulp-order"),
    concat = require("gulp-concat"),
    mainBowerFiles = require('main-bower-files');


gulp.task('build-dependencies', function() {
  console.log(mainBowerFiles("**/*.js"));
  return gulp.src(mainBowerFiles("**/*.js"))
    .pipe(flatten())
    .pipe(gulp.dest('public/javascripts'));
});
```

**Comment by jrgleason** [comment]
Rt actually already had that...

    [ '..proj\bower_components\\system.js\\dist\\system.js' ]
    [15:48:49] 'build-dependencies' errored after 16 ms
    [15:48:49] TypeError: dest.on is not a function

**Comment by jrgleason** [comment]
oops 

    mainBowerFiles = require('gulp-main-bower-files')

was needed instead of

    mainBowerFiles = require('main-bower-files')
