### ISSUE TITLE
Error occurs if bower_components is created on the fly (with gulp).

### ISSUE THREAD

**Issue by bayandin** [ck86/main-bower-files#69]
I use main-bower-file with gulp and gulp-bower plugin. My flow is: at first gulp-bower downloads bower components (and creates directory for them), after that main-bower-files collects them.

And I get an error because I don't have bower_components directory initially.

```
 Error: Bower components directory does not exist at /Users/bayandin/repos/example/bower_components
    at module.exports (/Users/bayandin/repos/example/node_modules/main-bower-files/lib/index.js:54:15)
    at Gulp.<anonymous> (/Users/bayandin/repos/example/gulpfile.js:9:24)
    at module.exports (/Users/bayandin/repos/example/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/bayandin/repos/example/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/bayandin/repos/example/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/bayandin/repos/example/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/bayandin/repos/example/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
```

Example of my gulpfile:
```js
var gulp = require('gulp');
var bower = require('gulp-bower');
var mainBowerFiles = require('main-bower-files');

gulp.task('default', function () {
    return bower()
        .pipe(gulp.src(mainBowerFiles()))
        .pipe(gulp.dest('static/lib'));
});
```

**Comment by bayandin** [comment]
In my case I fixed it by splitting the task into two with dependencies.
So issue may be closed if it is not a priority.

**Comment by lisapfisterer** [comment]
Could you post of your final working solution?

**Comment by ck86** [comment]
@lisapfisterer 

I guess the two tasks looks like:

```js
gulp.task('bower:install', function() {
  return bower().pipe(gulp.dest('bower_components'))
})

gulp.task('bower:copy', ['bower:install'], function() {
  return gulp.src(mainBowerFiles()).pipe(gulp.dest('static/lib'));
});
```

**Comment by lisapfisterer** [comment]
Thank you for the fast reply! This is really helpful.
