### ISSUE TITLE
Cannot find module 'main-bower-files'

### ISSUE THREAD

**Issue by git03394538** [ck86/main-bower-files#73]
My gulp task used to be Ok, but after today's update to version 2.6.0, my gulp can't find "main-bower-files" any more. 

Here's the sample gulp task I have tried:
```
var gulp = require('gulp');
var mainBowerFiles = require('main-bower-files');

gulp.task('try', function() {
    return gulp.src(mainBowerFiles()).pipe();
});
```
And here's the error I get after I execute 
> gulp try
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'main-bower-files'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ianchiu/workspace/BatonHunter/gulpfile.js:2:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Everything works fine after I downgrade to 2.5.0.
Is there any new changes that I didn't aware of or?
btw, I realize 2.6.0 automatically install grunt into my local node_modules folder, is this part of the new implementation too?

**Comment by ck86** [comment]
I will have look asap.

**Comment by Rob-pw** [comment]
Installing main-bower-files via npm results in an incomplete directory, after repeated attempts my main-bower-files still only contains: 

```
node_modules
tasks
  main-bower-files.js
package.json
README.md
```

**Comment by git03394538** [comment]
WOW, thanks @Rob-pw!! am looking at the latest changes in the code, as I am not really familiar with grunt, am still trying to put everything together. And see if can fix it.

**Comment by Fulkman** [comment]
The issue is in the package.json file.
Remove the `files` properties and it should be ok.

**Comment by gruppjo** [comment]
Having the same issue. the package.json reads:
```json
  "name": "main-bower-files",
  "version": "2.6.0",
  "description": "Get main files from your installed bower packages.",
  "main": "index.js",
   ...
```
but there is no index.js in the module folder:
![screen shot 2015-03-12 at 14 53 23](https://cloud.githubusercontent.com/assets/1370779/6619026/9a173b42-c8c7-11e4-8bf9-64d34216f257.png)

**Comment by mrbinky3000** [comment]
Adding ```"main": "tasks/main-bower-files.js",``` to the package.json file got it working, but then I ran into this:

```shell
TypeError: Object #<Object> has no method 'registerMultiTask'
    at module.exports (/var/www/launchrock-app/public/assets/lr-site-manager/node_modules/main-bower-files/tasks/main-bower-files.js:7:11)
    at Gulp.gulp.task.gulp.src.mainBowerFiles.debugging (/var/www/launchrock-app/public/assets/lr-site-manager/gulpfile.js:117:26)
    at module.exports (/var/www/launchrock-app/public/assets/lr-site-manager/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/launchrock-app/public/assets/lr-site-manager/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/launchrock-app/public/assets/lr-site-manager/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/launchrock-app/public/assets/lr-site-manager/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

**Comment by git03394538** [comment]
Thanks for the fast response :+1:  have anyone test the fix against Grunt? 
not sure if that line is added for grunt feature implementation ..
