### ISSUE TITLE
includeDev: inclusive | exclusive  "ReferenceError: ___ is not defined"

### ISSUE THREAD

**Issue by Brendonwbrown** [ck86/main-bower-files#91]
includeDev parameter will accept true or false but the readme recommends "inclusive" or "exclusive", which error out as undefined.

**Comment by ck86** [comment]
Can you show me when this ReferenceError occurs?

**Comment by Brendonwbrown** [comment]
Sure, I set the results of `mainBowerFiles` to a variable `load_paths`. I modify the contents later in a gulp task to give me directories for scss @imports.

```
var load_paths = mainBowerFiles({
      includeDev: true,
      base: 'components',
      filter: '**/*.{sass,scss}'
    });
```

The task runs perfectly works when `includeDev` is set to `true`. When set to `inclusive` I get the following:
```
ReferenceError: inclusive is not defined
    at Object.<anonymous> (/Users/brendonwbrown/Documents/www/Projects/rs.com form/gulpfile.js:30:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:181:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

**Comment by ck86** [comment]
Did you wrote something like that?

```js
var load_paths = mainBowerFiles({
      includeDev: inclusive,
      base: 'components',
      filter: '**/*.{sass,scss}'
    });
```

I think you forgot the quotes?

**Comment by ck86** [comment]
Hint: The `base` option should passed to the gulp.src options, not to the mainBowerFiles options.

**Comment by Brendonwbrown** [comment]
Yup, the quotes, a noob mistake. Please disregard this.

The bit of code works. Later I loop through results to pipe all parent directories of scss Bower packages to gulp-sass for @imports.
